title: Andy Huang # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! I enjoy the process of uncovering insightful information within data to help companies achieve their goals. 
  <br><br>
  I'm currently finishing up my MS in Marketing Analysis, and have taken courses on both Data Science group and Marketing group. Here I featured some of my previous projects that I enjoyed working on the most. 
  <br><br>
  <a href="https://www.linkedin.com/in/hungweihuang/> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
