title: ANDY HUANG # your name (or website title) here
logo: "/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my portfolio! My name is Andy, and I enjoy uncovering insights within data to support the organizations in achieving their goals.
  <br><br>
  For easy navigation, my projects are categorized into 5 categories: Advanced Data Analysis, Time Series Analysis & Forecasting, Data Analysis & Regression, Advanced Market Research, and Marketing Strategies & Planning.
  <br><br>
  <a href="https://www.linkedin.com/in/hungweihuang/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
